import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Notifications from "@/components/Notifications/Notifications";
import NavBar from "@/components/NavBar/NavBar";
import ProfileSettings from "@/components/Profile/ProfileSettings";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Контекстно мультиплеер",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <NavBar />
        <Notifications />
        <ProfileSettings />
        {children}
      </body>
    </html>
  );
}
